# Generated by Django 5.1.4 on 2025-08-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=150)),
                ('article', models.CharField(default='', max_length=1000)),
                ('short_description', models.CharField(default='', max_length=100)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
                ('written_by', models.CharField(default='', max_length=150)),
            ],
        ),
    ]
