# Generated by Django 5.1.4 on 2025-08-19 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description_geo', models.TextField()),
                ('short_description_geo', models.TextField()),
                ('description_eng', models.TextField()),
                ('short_description_eng', models.TextField()),
                ('uploaded_at', models.DateField()),
            ],
        ),
    ]
