# Generated by Django 5.1.4 on 2025-08-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='future_projects',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects_images/'),
        ),
    ]
