# Generated by Django 5.1.4 on 2025-08-19 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_future_projects_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='future_projects',
            name='image',
        ),
    ]
