# Generated by Django 5.1.4 on 2025-08-19 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_future_projects_uploaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
    ]
